acm-ucr/rishi-website

- src/app/page.js
- src/components/Button.jsx
I might be having some trouble with the spacing of border and text, but here is what it looks like so far
> Completed Button component

- src/components/home/Socials.jsx
- I already tried my best to match the tailwind width and height with figma, e.g for 238x268 px, I only can get roughly rem in tailwind like w-60 h-64. 
-  it seems icon pictures are not so clear if make it bigger
-  there is no link for facebook and highlander link, so I just put `<a herf="/" target="_blank"></a>`
-  not good at viewing figma design with two items gap ( hope  I can get some help with this problem)
> social jsx

- src/components/gallery/Options.jsx
> Options - Gallery

- package-lock.json
- package.json
- src/app/page.js
- src/components/Button.jsx
- src/components/gallery/Options.jsx
> Gallery - Options

- src/components/board/Member.jsx
> Member Card created

- package-lock.json
- package.json
- src/components/home/Mission.jsx
-Created mission page
-Needs help with positioning the texts. I believe the issue lies in the use of "top" and "left" in styling.
> Mission-Home 

- src/app/about/page.js
- src/app/board/page.js
- src/app/gallery/page.js
- src/app/page.js
- src/components/Heading.jsx
> Made heading component

- src/app/page.js
- src/components/home/Carousel.jsx
- src/data/carousel.js
- tailwind.config.js
- created carousel but image sizing is broken 
- added marquee function into tailwind config file
- created gallery.js in src/data
> created carousel

- src/app/gallery/[trip]/page.js
- src/components/home/Landing.jsx
- fixed horizontal scroll bug on landing page.
> fixed landing bug

- src/components/about/About.jsx
> Optimized for mobile responsiveness

- src/app/not-found.js
> 404 Page Updated

- src/components/Heading.jsx
- src/components/gallery/Options.jsx
I made "options font size the same as the heading font size" but maybe it needs to be extrabold?
> Gallery Button Font/Spacing Fixes

- src/components/board/Board.jsx
- src/components/board/Member.jsx
- src/data/staff.js
Need help fixing the sizing for the member components.
> Populate Board Data

- src/components/Button.jsx
-Updated font size
-Added button pop
> Button-Fixes

- src/data/gallery.js
I deleted the duplicates in india2014
> deleted the two sets of dup photos in india2014

- src/components/events/Calendar.jsx
- src/components/events/ToolBar.jsx
Made entire calendar visible on small screens and added the arrows on the sides for users to navigate the months on mobile
> Added Toolbar for mobile and made calendar visible on small screens

- src/components/home/Landing.jsx
> landing pic breakpoint

- src/app/layout.js
- src/components/Navigation.jsx
- made navbar fit on smaller screens 
- collapse  and toggle menu still doesn't work
> navbar changes

- src/app/about/page.js
- src/app/board/page.js
- src/app/gallery/page.js
> Added white spacing

- src/components/Button.jsx
> Restored Color to Orange

- src/components/Footer.jsx
- src/components/home/Socials.jsx
> removed underlines and changed blue icons to white

- src/components/gallery/GalleryImage.jsx
- unified sizing of images on gallery page
> gallery fixes

- src/components/Footer.jsx
> Hover Animation on Footer

- src/components/home/Socials.jsx
> removed shadow from icons and border has hover animation

- src/components/Footer.jsx
- src/components/board/Member.jsx
sent u a vid of the hover on discord
> adding hover animation

- src/components/gallery/Options.jsx
Hover animation on the buttons 
Me hovering over second button
> Added hover animation

- package-lock.json
- package.json
- src/components/events/Calendar.jsx
- src/components/events/CalendarApi.jsx
implemented google calendar api
> google calendar api

- src/components/Navigation.jsx
> Navbar Refresh Bug Fixed
